spring.application.name=empower

server.port=8085
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Allow all origins
spring.mvc.cors.allowed-origins=*

app.save.directory=\\\\devotex003\\OpenText\\EmpowerDocs