spring.application.name=empower

server.port=8085
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Allow all origins
spring.mvc.cors.allowed-origins=*

app.save.directory=\\\\devotex003\\OpenText\\EmpowerDocs

# Enable HTTPS using the same keystore as Empower
server.ssl.enabled=true
server.ssl.key-store=file:E:/TomEE/conf/bootstrap.keystore
server.ssl.key-store-type=JKS
server.ssl.key-store-password=password
server.ssl.key-alias=bootstrap